### PR TITLE
Setup workflow for linting and formatting

### PR DESCRIPTION
**Pull request by mariannerv**
- Created a GitHub Actions workflow to enforce code quality.
- Integrated Flake8 for linting and Black for formatting checks.
- The workflow runs on push and pull request events targeting the main branch.

### CODE REVIEW

**Review by JohananOppongAmoateng — CHANGES_REQUESTED** [review]
Please can you make the max length 80 characters. Also can you check to ensure the code passes all the linting and formatting checks. Thank you

**Review by JohananOppongAmoateng — APPROVED** [review]

**Comment by JohananOppongAmoateng** [comment]
@mariannerv Thank you for your contribution.

**Comment by mariannerv** [comment]
No worries! Thank you for letting me contribute!

**Comment by JohananOppongAmoateng** [comment]
@mariannerv Forgot to add this please fix the merge conflicts.

**Comment by mariannerv** [comment]
My bad, should be good now

**Pull request merged**
